### ISSUE TITLE
Consider using a config file instead of environment variables

### ISSUE THREAD

**Issue by YtvwlD** [chaosdorf/telemete#4]
docker supports configuration files for containers in the swarm mode which we'll be using shortly™. (It can also be emulated by simply mounting the config file read-only.)

I propose the following format which uses [TOML](https://github.com/toml-lang/toml):

```toml
[mete_connection]
base_url = "http://mete/"

[initial_admin]
telegram_id = 1234
telegram_handle = "foo"
mete_id = 5678
```

(also see #2 and #3)

Edit: Using TOML instead of INI because of ints being ints.
